# Generated by Django 3.0.3 on 2020-04-15 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, default='')),
                ('major', models.CharField(blank=True, choices=[('Undecided', 'Undecided'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Earth Sciences', 'Earth Sciences'), ('Health Sciences', 'Health Sciences'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], default='Undecided', max_length=30)),
                ('year_in_school', models.CharField(blank=True, choices=[('First Year', 'First'), ('Second Year', 'Second'), ('Third Year', 'Third'), ('Fourth Year', 'Fourth'), ('Graduate Student', 'Grad Student')], default='First Year', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
