# Generated by Django 3.0.3 on 2020-04-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, choices=[('Undecided', 'Undecided'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Earth Sciences', 'Earth Sciences'), ('Health Sciences', 'Health Sciences'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics')], default='Undecided', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('First Year', 'First'), ('Second Year', 'Second'), ('Third Year', 'Third'), ('Fourth Year', 'Fourth'), ('Graduate Student', 'Grad Student')], default='First Year', max_length=30),
        ),
    ]
