# Generated by Django 3.0.3 on 2020-04-14 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200414_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AddField(
            model_name='like',
            name='profiles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.AddField(
            model_name='like',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
    ]
