# Generated by Django 3.0.3 on 2020-04-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200414_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='profiles',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='user',
        ),
    ]
