# Generated by Django 3.0.3 on 2020-04-15 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20200414_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
