services:
- postgresql
language: python
python:
- 3.7.1
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: YAv/hue5L3fFkn6IZNzRd2kppESv2YwgfCnsC8/O6IznozTd1fiFAWHB7IBhFp9rUOOF6DtOuI1XKMFK+8nf91Qkc4QNm79qksNwfNTMBRVn4VoRC3jKFead9uA9iXk2zHL8N/rQ7P1Il1D9FW55Lu+QvG3rwqTSa/MgqZspOLkHraV/lmZmcE/Ws8lNiFhVI5fUG5GiXhMD/3al+Wx+x+aOZ8/TvmGiO/hZHgm6ENSkmLrq/FFc6GFKJBxLxVRGb8aVP54LExvwB9LcA8g054+qzlyxAf/hjWWrRwV1Uh88f0SMX167FnC1GL+h3sza9XLdU/mKJVHSw1TXhw9b+qNzHoOfN90RxCZ5d4vOvzUORUYRgkJTpsaDgup0f75Jf0k1N5v292LH3tL8jzkriWshyhGpv7sejTyLB4uCa+19WVVX9/YGZTNxwSORmklURCW0TAnU4ridgjdIFNOOXVN9NWRu2yuAZikaFKhoQwdmIbvIDh+rZhOavbJlysvCACDbwp0VnaPbF6mOULrbiFyVamrHN5W/ZexdxCurBrOAzFLEWk5V7jF6YivZQxb5rznW2tqWgOyujNo8X2+ob1hUX8bC3G7fW4BcQlpxQruYBt888/1HkqTrP78mrkl9LmF5xyfbOdD9BnKN7xBzh+lgmLnRvTP9E4P0O5atQeE=
  app: find-a-qt2
  on:
    repo: uva-cs3240-s20/project-101-find-a-qt
