language: python
python:
- 3.7.1
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: d25a7f53-92ae-4a18-84f2-0b1ef4470318
  app: find-a-qt2
  on:
    repo: uva-cs3240-s20/project-101-find-a-qt
