language: python
python:
- '3.7.1'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: j1X/p1VmF/GHxyp+gPKTn5ZaabBKg08vuCExP0Bhem99McN4gFjRoBgkB2G1ZMqyDHysvxblqlzBwk6YpNWJkLsRK9msTLqBElntIlPblxF1lFdEHmI1U1iJTbqGiUYHWwiiM9jb8MX2nQEPU7FuCFx/rSU49rwXkHI6J/QTW16wwaa+OjAvHduK3g5snqIk4tj4L/P9yCH29BlLFkDUE/F5gw8/mKKBXozP20+/LEjMwgtFvAaUQ1oS4cJM1/SlD57l/AgNyZ0laPy9Y8dEcp+AOOb7pxRFxPogdjbeH6jt7AeVwmre9twuMosOc1VAZlFxeiTjmvNulphzaVHMlJy9evPcMbbsDcyQgISu1ktyEq04dmd31tG2rbugEXzsUnnNF6nq9V8mOiE9SeNIiCu3+KZguhuVVLgpMyrJIqE4N/EWMEfW6i20ht6Xpm7fUj0J8geQpI7hWEV9jjyja/Q+Y6p8dykq0Srn71MHZEnAyL0NhcCgerHcQb2UTjZHCXARIxdlqxkvd/7blH4UYJ0VhIjt1ye8B0wlArXVM6JbgoxUNrV31HhfijsjqdmxHR1N4epRkTclPEITDItvvJUAjuXdz/SnipojtXo3BPaoSOCkEOe5dym6ZoG/eXxCK7W7wUFOzBa3LgSpyH7fQkIymODINDTxEp2cqjB7bjU=
  app: find-a-qt2
  on:
    repo: uva-cs3240-s20/project-101-find-a-qt
