services:
- postgresql
language: python
python:
- 3.7.1
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: b3df8db7-68c4-4754-b068-a4f813ab1995
  app: find-a-qt2
  on:
    repo: uva-cs3240-s20/project-101-find-a-qt
