# Generated by Django 3.0.3 on 2020-04-05 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_a_qt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('topic', models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30)),
                ('class_name', models.CharField(default='', max_length=50)),
                ('author_name', models.CharField(default='Anonymous', max_length=50)),
                ('session_date', models.DateField(default=datetime.datetime.now)),
                ('session_time', models.TimeField(default=datetime.datetime.now)),
                ('time_submission', models.DateTimeField(auto_now=True)),
                ('urgency', models.CharField(choices=[('Due immediately', 'Due immediately'), ('Due within a week', 'Due within a week'), ('No rush', 'No rush')], default='No rush', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='question_images/')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_tutored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='major',
            field=models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('time_submission', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_a_qt.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
