# Generated by Django 3.0.3 on 2020-03-01 19:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('major', models.CharField(default='Undecided', max_length=55)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='1-800', max_length=128, region=None, unique=True)),
                ('name', models.CharField(default='John Doe', max_length=50)),
                ('bio', models.CharField(default='Hey! I am using Find a QT!', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=55),
        ),
    ]
