# Generated by Django 3.0.3 on 2020-02-28 01:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0002_auto_20200227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_Tutor', models.CharField(max_length=50)),
                ('last_name_Tutor', models.CharField(max_length=50)),
                ('bio_Tutor', models.CharField(max_length=500)),
                ('phone_number_Tutor', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('major_Tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('minor_Tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('year_Tutor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
