# Generated by Django 3.0.3 on 2020-03-02 00:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0002_auto_20200301_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='major',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True),
        ),
    ]
