# Generated by Django 3.0.3 on 2020-03-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0002_tutor_number_tutored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='major',
            field=models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30),
        ),
    ]
