# Generated by Django 3.0.3 on 2020-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0002_auto_20200227_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
