# Generated by Django 3.0.3 on 2020-02-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0003_tutor'),
        ('find_a_qt', '0003_auto_20200227_1556'),
    ]

    operations = [
    ]
