# Generated by Django 3.0.3 on 2020-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0003_remove_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
