# Generated by Django 3.0.3 on 2020-03-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0003_auto_20200322_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='class_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('UNDE', 'Undecided'), ('ASTR', 'Astronomy'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENGR', 'Engineering'), ('ES', 'Earth Sciences'), ('HS', 'Health Sciences'), ('IT', 'Information Technology'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], default='UNDE', max_length=30),
        ),
    ]
