# Generated by Django 3.0.3 on 2020-03-02 00:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0003_auto_20200302_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
