# Generated by Django 3.0.3 on 2020-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0004_auto_20200322_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
