# Generated by Django 3.0.3 on 2020-04-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0004_auto_20200411_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, upload_to='answer_images/'),
        ),
    ]
