# Generated by Django 3.0.3 on 2020-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0004_auto_20200411_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Earth Sciences', 'Earth Sciences'), ('Health Sciences', 'Health Sciences'), ('Information Technology', 'Information Technology'), ('Math', 'Mathematics'), ('Physics', 'Physics')], default='Undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Earth Sciences', 'Earth Sciences'), ('Health Sciences', 'Health Sciences'), ('Information Technology', 'Information Technology'), ('Math', 'Mathematics'), ('Physics', 'Physics')], default='Undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='major',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Earth Sciences', 'Earth Sciences'), ('Health Sciences', 'Health Sciences'), ('Information Technology', 'Information Technology'), ('Math', 'Mathematics'), ('Physics', 'Physics')], default='Undecided', max_length=30),
        ),
    ]
