# Generated by Django 3.0.3 on 2020-02-28 02:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0004_merge_20200227_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='bio_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='first_name_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='major_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='minor_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='phone_number_Tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='year_Tutor',
        ),
        migrations.AddField(
            model_name='tutor',
            name='major',
            field=models.CharField(default='Undecided', max_length=55),
        ),
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='John Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1-800', max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
