# Generated by Django 3.0.3 on 2020-04-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0005_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(choices=[(1, 'D'), (2, 'S'), (3, 'H'), (4, 'C'), (5, 'A')]),
        ),
    ]
