# Generated by Django 3.0.4 on 2020-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0005_question_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
