# Generated by Django 3.0.3 on 2020-04-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0006_auto_20200413_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='post',
        ),
        migrations.AddField(
            model_name='answer',
            name='Question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='find_a_qt.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
