# Generated by Django 3.0.4 on 2020-04-01 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0006_auto_20200401_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='session_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 0, 28, 36, 121285, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='urgency',
            field=models.CharField(choices=[('NW', 'Due immediately'), ('LT', 'Due within a week'), ('WH', 'No rush')], default='WH', max_length=2),
        ),
    ]
