# Generated by Django 3.0.3 on 2020-03-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0006_auto_20200301_1939'),
        ('find_a_qt', '0006_auto_20200301_1921'),
    ]

    operations = [
    ]
