# Generated by Django 3.0.3 on 2020-04-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0007_auto_20200414_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
    ]
