# Generated by Django 3.0.4 on 2020-04-01 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0007_auto_20200401_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='session_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 0, 33, 25, 460896, tzinfo=utc)),
        ),
    ]
