# Generated by Django 3.0.3 on 2020-04-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0008_auto_20200414_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='post',
        ),
    ]
