# Generated by Django 3.0.3 on 2020-04-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0012_auto_20200415_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
