# Generated by Django 3.0.4 on 2020-04-03 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0014_auto_20200403_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='session_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='session_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
