# Generated by Django 3.0.3 on 2020-04-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0014_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
