# Generated by Django 3.0.4 on 2020-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0015_auto_20200403_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='urgency',
            field=models.CharField(choices=[('Due immediately', 'Due immediately'), ('Due within a week', 'Due within a week'), ('No rush', 'No rush')], default='No rush', max_length=30),
        ),
    ]
