# Generated by Django 3.0.3 on 2020-04-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0015_remove_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='answer_images/'),
        ),
    ]
