# Generated by Django 3.0.3 on 2020-04-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0005_auto_20200414_1350'),
        ('find_a_qt', '0016_auto_20200415_0101'),
    ]

    operations = [
    ]
