# Generated by Django 3.0.3 on 2020-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='bio',
            new_name='bio_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='first_name',
            new_name='first_name_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='last_name',
            new_name='last_name_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='major',
            new_name='major_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='minor',
            new_name='minor_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='phone_number',
            new_name='phone_number_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='year',
            new_name='year_tutor',
        ),
    ]
