# Generated by Django 3.0.3 on 2020-02-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_qt', '0002_auto_20200227_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='bio_tutor',
            new_name='bio_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='first_name_tutor',
            new_name='first_name_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='last_name_tutor',
            new_name='last_name_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='major_tutor',
            new_name='major_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='minor_tutor',
            new_name='minor_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='phone_number_tutor',
            new_name='phone_number_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='year_tutor',
            new_name='year_Tutor',
        ),
    ]
